#version 460

#extension GL_GOOGLE_include_directive : require

#include "ray.comp"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba8) uniform image2D out_image;
layout(set = 0, binding = 1, rgba8) uniform image3D model;
layout(push_constant) uniform PushConstants {
    vec3 camera_position;
} push_constants;

const float viewportHeight = 50;
const float focalLength = 1;

vec4 getVoxelAtCoord(vec3 coord, AABB aabb) {
    ivec3 voxelCoord = ivec3(coord - aabb.minPos);
    return imageLoad(model, voxelCoord);
}

vec2 intersection(Ray ray, AABB aabb) {
    vec3 inverse = 1 / ray.direction;
    vec3 t_min = (aabb.minPos - ray.origin) * inverse;
    vec3 t_max = (aabb.minPos + aabb.size - ray.origin) * inverse;
    vec3 t1 = min(t_min, t_max);
    vec3 t2 = max(t_min, t_max);
    float t_near = max(max(t1.x, t1.y), t1.z);
    float t_far = min(min(t2.x, t2.y), t2.z);
    return vec2(t_near, t_far);
}

vec4 traverse_and_get_color(Ray ray, vec2 tMinMax, AABB aabb) {
    // 0 if the sign is -1.0 and 1 if the sign is 1.0
    vec3 planeSelector = sign(ray.direction) / vec3(2) + vec3(1) / vec3(2);
    float tMin = tMinMax.x;
    float tMax = tMinMax.y;
    vec3 currentPoint = clamp(floor(ray.origin + tMin * ray.direction), aabb.minPos, aabb.minPos + aabb.size);
    vec3 endPoint = ray.origin + ray.direction * tMax;
    // this will select the "next" plane that the ray will intersect with.
    // See https://www.youtube.com/watch?v=ztkh1r1ioZo for more info
    vec3 integerPlanes = currentPoint + planeSelector;
    vec3 t = integerPlanes / ray.direction - ray.origin / ray.direction;
    vec3 planeStep = sign(ray.direction);
    vec3 tDelta = abs(1 / ray.direction);
    uint steps = 0;
    vec3 maxPoint = aabb.minPos + aabb.size;

    // while the current position falls within the bounding box
    while (all(greaterThanEqual(currentPoint, aabb.minPos)) && all(lessThanEqual(currentPoint, maxPoint))) {
        vec4 voxelValue = getVoxelAtCoord(currentPoint, aabb);
        if (voxelValue != vec4(0)) {
            return vec4(0.1, 0.85, 0.1, 1);
        }
        steps++;
        if (t.x < t.y) {
            if (t.x < t.z) {
                currentPoint.x += planeStep.x;
                t.x += tDelta.x;
            } else {
                currentPoint.z += planeStep.z;
                t.z += tDelta.z;
            }
        } else {
            if (t.y < t.z) {
                currentPoint.y += planeStep.y;
                t.y += tDelta.y;
            } else {
                currentPoint.z += planeStep.z;
                t.z += tDelta.z;
            }
        }
    }
    float maxSteps = float(aabb.size.x + aabb.size.y + aabb.size.z);
    float stepRatio = float(steps) / maxSteps;
    return vec4(stepRatio, stepRatio, stepRatio, 1);
}

vec4 rayColor(Ray ray) {
    vec3 modelPosition = vec3(0, 0, 0);
    ivec3 modelSize = imageSize(model);
    vec3 unit = normalize(ray.direction);
    float t = 0.5 * (unit.x + 1);
    vec4 voxel = imageLoad(model, ivec3(10, 10, 10));
    vec4 startColor = vec4(0, 0, 0, 1);
    vec4 endColor = vec4(0.5, 0.5, 0.5, 1);
    AABB aabb = AABB(modelPosition, modelSize);
    vec2 tMinMax = intersection(ray, aabb);
    float tMin = tMinMax.x;
    float tMax = tMinMax.y;
    if (tMin >= tMax) {
        return (1.0 - t) * startColor + t * endColor;
    }
    return traverse_and_get_color(ray, tMinMax, aabb);
}

void main() {
    vec2 imgSize = vec2(imageSize(out_image));

    if (any(greaterThanEqual(gl_GlobalInvocationID.xy, imgSize))) return;

    vec3 up_vector = vec3(0, -1, 0);

    float aspectRatio = float(imgSize.x) / float(imgSize.y);
    float viewportWidth = aspectRatio * viewportHeight;
    vec3 camera_center = push_constants.camera_position;
    vec3 camera_relative_foward = normalize(-camera_center);
    vec3 camera_relative_right = normalize(cross(camera_relative_foward, up_vector));
    vec3 camera_relative_down = cross(camera_relative_foward, camera_relative_right);
    vec3 viewport_right_vector = viewportWidth * camera_relative_right;
    vec3 viewport_down_vector = viewportHeight * camera_relative_down;

    vec3 pixel_delta_right = viewport_right_vector / imgSize.x;
    vec3 pixel_delta_down = viewport_down_vector / imgSize.y;

    vec3 viewportUpperLeft = -viewport_down_vector * 0.5 - viewport_right_vector * 0.5;
    vec3 topLeftPixel = viewportUpperLeft + 0.5 * (pixel_delta_down + pixel_delta_right);

    vec3 pixelCenter = topLeftPixel + gl_GlobalInvocationID.x * pixel_delta_right + gl_GlobalInvocationID.y * pixel_delta_down;
    vec3 rayDirection = normalize(pixelCenter - camera_center);
    Ray ray = Ray(camera_center, rayDirection);
    vec4 color = rayColor(ray);
    imageStore(out_image, ivec2(gl_GlobalInvocationID.xy), rayColor(ray));
    // imageStore(out_image, ivec2(gl_GlobalInvocationID.xy), vec4(rayDirection.xyz, 0));
}
