#version 460

#extension GL_GOOGLE_include_directive : require

#include "svt.comp"
#include "shader_inputs.comp"
#include "ray.comp"
#include "traversal.comp"
#include "gradient.comp"

void main() {
    uvec2 imgSize = uvec2(imageSize(out_image));
    if (any(greaterThanEqual(gl_GlobalInvocationID.xy, imgSize))) return;

    uint random_seed = generate_seed(gl_GlobalInvocationID.xy, push_constants.frame_number);

    Ray ray = generate_ray(push_constants);
    bool show_steps = bool((push_constants.shader_flags >> 0) & 1);
    bool show_normals = bool((push_constants.shader_flags >> 1) & 1);
    bool show_hit_position = bool((push_constants.shader_flags >> 2) & 1);


    // BOUNCE!

    // const vec3 sky_color = vec3(0.156862745);
    const vec3 sky_color = vec3(1);
    const vec3 material_emission = vec3(0);
    uint bounce_number;
    uint max_hits = 2;
    vec3 final_light_color = vec3(0);
    vec3 throughput = vec3(1);

    for(bounce_number=0;bounce_number<max_hits;bounce_number++) {
        HitInfo hit = cast_ray(push_constants.model_scale, ray);

        if(hit.hit) {
            // The first byte should be `a` but its being interpreted as r
            u8vec4 abgr_color = color_palette.palette[hit.palette_index];
            vec3 surface_color = vec3(abgr_color.wzy) / 255; // floating point image type
            // the color only contributes as much as the total reflectance of all the surfaces we've hit before allow
            final_light_color += material_emission * throughput;

            // the next bounce will be attenuated by the reflectance of this surface
            throughput *= surface_color;
        } else {
            final_light_color += sky_color * throughput;
            break;
        }

        ray.direction = normalize(hit.normal + random_in_unit_sphere(random_seed));
        ray.origin = hit.position + hit.normal * 0.0001;
    }

    float weight = 1.0 / (push_constants.frame_number + 1);

    vec3 previous_color = imageLoad(out_image, ivec2(gl_GlobalInvocationID.xy)).xyz;

    imageStore(out_image, ivec2(gl_GlobalInvocationID.xy), vec4(mix(previous_color, final_light_color, weight), 1));
}
