struct Ray {
    vec3 origin;
    vec3 direction;
};

struct AABB {
    vec3 minPos;
    vec3 size;
};

Ray generate_ray(PushConstants push_constants) {
    // TODO: generate this with a matrix instead: https://www.scratchapixel.com/lessons/3d-basic-rendering/ray-tracing-generating-camera-rays/generating-camera-rays.html
    // If you generate a matrix you can just pass the matrix to this function instead of all the push constants
    vec3 top_left_pixel = push_constants.top_left_pixel;
    vec3 pixel_delta_right = push_constants.pixel_delta_right;
    vec3 pixel_delta_down = push_constants.pixel_delta_down;
    vec3 camera_center = vec3(push_constants.camera_x, push_constants.camera_y, push_constants.camera_z);
    vec3 pixelCenter = top_left_pixel + gl_GlobalInvocationID.x * pixel_delta_right + gl_GlobalInvocationID.y * pixel_delta_down;
    vec3 rayDirection = normalize(pixelCenter - camera_center);
    Ray ray = Ray(camera_center, rayDirection);
    return ray;
}

vec3 intersectAABB(Ray ray, AABB aabb) {
    vec3 inverse = 1 / ray.direction;
    vec3 t_min = (aabb.minPos - ray.origin) * inverse;
    vec3 t_max = (aabb.minPos + aabb.size - ray.origin) * inverse;
    vec3 t1 = min(t_min, t_max);
    vec3 t2 = max(t_min, t_max);
    float t_near = max(max(t1.x, t1.y), t1.z);
    float t_far = min(min(t2.x, t2.y), t2.z);
    float input_axis = t_near == t1.x ? 0 : (t_near == t1.y ? 1 : 2);
    return vec3(t_near, t_far, input_axis);
}

uint random_u32(inout uint seed) {
    uint state = seed * 747796405 + 2891336453;
    uint word = ((state >> ((state >> 28) + 4)) ^ state) * 277803737;
    uint rand = (word >> 22) ^ word;
    seed = rand;
    return rand;
}

uint generate_seed(uvec2 uv, uint frame_number) {
    uint seed = uv.x ^ (uv.y << 16);
    seed = random_u32(seed);
    seed ^= frame_number * 1234;
    return  seed;
}

vec3 random_in_unit_sphere(inout uint seed) {
    // Getting an angle and a height to sind a random vector in a unit sphere
    const float PI_2 = 6.283185307179586;
    // creates 2 16 bit random numbers between 0 & 1
    vec2 zero_to_one = vec2((uvec2(random_u32(seed)) >> uvec2(0, 16)) & 65535) / 65536.0;
    float horizontal_plane_angle = zero_to_one.x * PI_2;
    // From -1 to 1
    float height = zero_to_one.y * 2 - 1;
    float horizontal_plane_length = sqrt(1 - height * height); // r = 1.0, r = horizontal_plan_length^2 + height^2, therefore horizontal_plan_length = sqrt(1-height^2)
    return vec3(sin(horizontal_plane_angle) * horizontal_plane_length,height,cos(horizontal_plane_angle) * horizontal_plane_length);
}
