#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba8) uniform image2D out_image;

layout(set = 0, binding = 1) readonly buffer Svt
{
    SvtNode nodes[];
} svt;

layout(set = 0, binding = 2) readonly buffer LeafData
{
    uint8_t data[];
} leaf_data;

layout(set = 0, binding = 3) uniform Colorpalette {
    vec4 palette[256];
} color_palette;

struct PushConstants {
    vec3 top_left_pixel;
    float camera_x;
    vec3 pixel_delta_right;
    float camera_y;
    vec3 pixel_delta_down;
    float camera_z;
    uint8_t shader_flags;
    uint8_t model_scale;
    uint8_t padding_for_pc_range;
    uint8_t padding_for_pc_range2;
};

layout(push_constant) uniform PushConstantBlock {
    PushConstants push_constants;
};
