#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

struct SvtNode {
    uint is_leaf_and_child_pointer;
    uint child_mask_high;
    uint child_mask_low;
};

bool is_leaf(SvtNode node) {
    return node.is_leaf_and_child_pointer >> 31 == 1;
}

bool has_child(uint64_t node_child_mask, uint child_index) {
    return ((node_child_mask >> child_index) & 1) == 1;
}

uint get_child_pointer(SvtNode node) {
    return node.is_leaf_and_child_pointer & 0x7FFFFFFF;
}

uint64_t get_child_mask(SvtNode node) {
    return uint64_t(node.child_mask_high) << 32 | uint64_t(node.child_mask_low);
}
